/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ffiJava */

#ifndef _Included_ffiJava
#define _Included_ffiJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ffiJava
 * Method:    sinc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_ffiJava_sinc
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ffiJava
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ffiJava_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
